### ISSUE TITLE
小米6 MIUI 9.5，稳定版

### ISSUE THREAD

**Issue by yknn** [sendtion/XRichText#20]
```java
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/nineoldandroids/view/ViewHelper;
        at me.iwf.photopicker.fragment.ImagePagerFragment.runEnterAnimation(ImagePagerFragment.java:190)
        at me.iwf.photopicker.fragment.ImagePagerFragment.access$300(ImagePagerFragment.java:29)
        at me.iwf.photopicker.fragment.ImagePagerFragment$1.onPreDraw(ImagePagerFragment.java:151)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2362)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1411)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6785)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:968)
        at android.view.Choreographer.doCallbacks(Choreographer.java:780)
        at android.view.Choreographer.doFrame(Choreographer.java:715)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:954)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6665)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.nineoldandroids.view.ViewHelper" on path: DexPathList[[zip file "/data/app/com.sendtion.xrichtext-cHuwTuKeTpm2xd54fwRCvg==/base.apk", zip file "/data/app/com.sendtion.xrichtext-cHuwTuKeTpm2xd54fwRCvg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.sendtion.xrichtext-cHuwTuKeTpm2xd54fwRCvg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.sendtion.xrichtext-cHuwTuKeTpm2xd54fwRCvg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.sendtion.xrichtext-cHuwTuKeTpm2xd54fwRCvg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.sendtion.xrichtext-cHuwTuKeTpm2xd54fwRCvg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.sendtion.xrichtext-cHuwTuKeTpm2xd54fwRCvg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.sendtion.xrichtext-cHuwTuKeTpm2xd54fwRCvg==/split_lib_slice_5_apk.apk", zip file "/data/app/com.sendtion.xrichtext-cHuwTuKeTpm2xd54fwRCvg==/split_lib_slice_6_apk.apk", zip file "/data/app/com.sendtion.xrichtext-cHuwTuKeTpm2xd54fwRCvg==/split_lib_slice_7_apk.apk", zip file "/data/app/com.sendtion.xrichtext-cHuwTuKeTpm2xd54fwRCvg==/split_lib_slice_8_apk.apk", zip file "/data/app/com.sendtion.xrichtext-cHuwTuKeTpm2xd54fwRCvg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.sendtion.xrichtext-cHuwTuKeTpm2xd54fwRCvg==/lib/arm64, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
```

**Comment by sendtion** [comment]
是崩溃了吗？什么时候出现的？可否复现？

**Comment by sendtion** [comment]
在项目中引入依赖库试试：
compile 'com.nineoldandroids:library:2.4.0'
