### ISSUE TITLE
插入图片报错

### ISSUE THREAD

**Issue by Average77** [sendtion/XRichText#34]
ClassCastException: com.bumptech.glide.RequestManager cannot be cast to com.sendtion.xrichtext.GlideRequests
                                                                             at com.sendtion.xrichtext.GlideApp.with(GlideApp.java:88)
                                                                             at com.sendtion.xrichtext.RichTextEditor.addImageViewAtIndex(RichTextEditor.java:423)
                                                                             at com.sendtion.xrichtext.RichTextEditor.insertImage(RichTextEditor.java:357)
                                                                             at com.sendtion.xrichtext.RichTextEditor.insertImage(RichTextEditor.java:340)

**Comment by Average77** [comment]
richText.insertImage(s, richText.getMeasuredWidth());   一到这一行就报这个错，是因为我的glide版本低的缘故么

**Comment by Average77** [comment]
emmm是我glide版本的问题。。
